<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CafeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('cafes')->insert([
            [
                'namaCafe' => 'Blanco Coffee and Books',
                'gambarCafe' => 'blanco.jpg',
                'alamatCafe' => 'Jl. Kranggan No.30, Cokrodiningratan, Kec. Jetis, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55233',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.78116364,
                'longitude' => 110.36605445,
                'hargaMin' => 22000,
                'hargaMax' => 55000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe trendi dengan suasana nyaman untuk bersantai sambil membaca buku atau mengerjakan tugas.',
            ],
            [
                'namaCafe' => 'Silol Kopi and Eatery',
                'gambarCafe' => 'silol.jpg',
                'alamatCafe' => 'Jl. Suroto, Kotabaru, Kec. Gondokusuman, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55224',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.78439152,
                'longitude' => 110.37563277,
                'hargaMin' => 5000,
                'hargaMax' => 185000,
                'kebutuhan' => '{"kerja": false, "nugas": false, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe buka 24 jam yang cocok untuk rapat atau nongkrong dengan teman-teman di suasana santai.',
            ],
            [
                'namaCafe' => 'Jeeva Yogyakarta',
                'gambarCafe' => 'jeeva.jpg',
                'alamatCafe' => 'Jl. Suhartono No.2, Kotabaru, Kec. Gondokusuman, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55224',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.78476474,
                'longitude' => 110.37662659,
                'hargaMin' => 18000,
                'hargaMax' => 142000,
                'kebutuhan' => '{"kerja": false, "nugas": false, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe dengan suasana hangat untuk nongkrong bersama teman dan menikmati menu yang variatif.',
            ],
            [
                'namaCafe' => 'Lunaria Coffee Yogyakarta',
                'gambarCafe' => 'lunaria.jpg',
                'alamatCafe' => 'Jl. Gedongkiwo No.29, Gedongkiwo, Kec. Mantrijeron, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55142',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.8134467,
                'longitude' => 110.35486396,
                'hargaMin' => 25000,
                'hargaMax' => 42000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe minimalis yang cocok untuk bekerja, belajar, atau bersantai dengan suasana tenang.',
            ],
            [
                'namaCafe' => 'Tanamera Coffee Yogyakarta',
                'gambarCafe' => 'tanamera.jpg',
                'alamatCafe' => 'Jl. Jend. Sudirman No.3, Cokrodiningratan, Kec. Jetis, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55233',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.78231635,
                'longitude' => 110.36838144,
                'hargaMin' => 25000,
                'hargaMax' => 68000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe modern dengan kopi spesialti dan suasana yang mendukung produktivitas.',
            ],
            [
                'namaCafe' => 'Legend Coffee',
                'gambarCafe' => 'legend.jpg',
                'alamatCafe' => 'Jl. Abu Bakar Ali No.24-26, Kotabaru, Kec. Gondokusuman, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55224',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.78800075,
                'longitude' => 110.37339481,
                'hargaMin' => 4000,
                'hargaMax' => 70000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe serba guna untuk kerja, belajar, atau berkumpul dengan teman hingga larut malam.',
            ],
            [
                'namaCafe' => 'Nol Kilometer Coffee and Tea Yogyakarta',
                'gambarCafe' => 'nolkilometer.jpg',
                'alamatCafe' => 'Jl. Pangurakan No.04, Ngupasan, Kec. Gondomanan, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55122',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.80161145,
                'longitude' => 110.36530609,
                'hargaMin' => 11000,
                'hargaMax' => 61000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Lokasi strategis dekat nol kilometer, ideal untuk bekerja atau bersantai dengan teman.',
            ],
            [
                'namaCafe' => 'Simetri Coffee Roaster',
                'gambarCafe' => 'simetri.jpg',
                'alamatCafe' => 'Jl. Sabirin No.20, Kotabaru, Kec. Gondokusuman, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55224',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.78417392,
                'longitude' => 110.37364279,
                'hargaMin' => 25000,
                'hargaMax' => 55000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe spesialti dengan suasana nyaman untuk bekerja atau sekadar menikmati kopi.',
            ],
            [
                'namaCafe' => 'Secret Garden Coffee and Chocolate',
                'gambarCafe' => 'secret garden.jpg',
                'alamatCafe' => '59X3+RHV, Jl. Prof. DR. Ki Amri Yahya No.2, Pakuncen, Wirobrajan, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55253',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.80010395,
                'longitude' => 110.35493998,
                'hargaMin' => 15000,
                'hargaMax' => 65000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kopi, camilan, dan hidangan manis kasual di tempat outdoor nyaman dengan tanaman hijau, lampu senar & gazebo.',
            ],
            [
                'namaCafe' => 'Loko Coffee',
                'gambarCafe' => 'loko.jpg',
                'alamatCafe' => 'Komp. Ps. Kembang, Jl. Ps. Kembang, Sosromenduran, Gedong Tengen, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55271',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.78954838,
                'longitude' => 110.36503734,
                'hargaMin' => 5000,
                'hargaMax' => 35000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Makanan lezat serta menu besar es dan minuman panas yang ditawarkan di kedai santai yang memiliki teras.',
            ],
            [
                'namaCafe' => 'Sapulu Coffee',
                'gambarCafe' => 'sapulu.jpg',
                'alamatCafe' => 'Jl. Panembahan Mangkurat No.10, Panembahan, Kecamatan Kraton, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55131',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.80686119,
                'longitude' => 110.36712671,
                'hargaMin' => 18000,
                'hargaMax' => 50000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Tempat nyaman dengan pilihan kopi terbaik untuk pengunjung yang mencari suasana tenang di tengah kota.',
            ],
            [
                'namaCafe' => 'Pixel Coffee',
                'gambarCafe' => 'pixel.jpg',
                'alamatCafe' => 'Jl. Tirtodipuran No.52, Mantrijeron, Kec. Mantrijeron, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55143',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.81871308,
                'longitude' => 110.36765214,
                'hargaMin' => 18000,
                'hargaMax' => 160000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe modern dengan suasana stylish dan menu yang beragam, cocok untuk nongkrong maupun bekerja.',
            ],
            [
                'namaCafe' => 'Taru Martani Coffee and Resto',
                'gambarCafe' => 'tarumartani.jpg',
                'alamatCafe' => 'Jl. Kompol Bambang Suprapto No.2A, Baciro, Kec. Gondokusuman, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55225',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.79086570,
                'longitude' => 110.38218702,
                'hargaMin' => 15000,
                'hargaMax' => 50000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe kasual dengan tempat duduk di taman, yang menawarkan kopi, minuman khas, dan hidangan lokal.',
            ],
            [
                'namaCafe' => 'Awor Coffee',
                'gambarCafe' => 'awor.jpg',
                'alamatCafe' => 'YAP SQUARE B11, Jl. C. Simanjuntak, Terban, Kec. Gondokusuman, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55223',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.78015891,
                'longitude' => 110.37428796,
                'hargaMin' => 20000,
                'hargaMax' => 45000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Tempat nyaman dengan nuansa santai yang menawarkan kreasi minuman berbahan espresso, camilan kafe & pastri.',
            ],
            [
                'namaCafe' => 'Filosofi Kopi',
                'gambarCafe' => 'filosofi kopi.jpeg',
                'alamatCafe' => 'Jl. Pandhawa No.001/17, Tegal Rejo, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.72748599,
                'longitude' => 110.37760669,
                'hargaMin' => 20000,
                'hargaMax' => 44000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe populer dengan menu kopi khas yang memanjakan pecinta kopi dengan konsep sederhana namun elegan.',
            ],
            [
                'namaCafe' => 'Space Roastery HQ',
                'gambarCafe' => 'space roastery hq.jpg',
                'alamatCafe' => 'Gg. Loncang No.88, Rogoyudan, Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55284',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.76593047,
                'longitude' => 110.36166490,
                'hargaMin' => 20000,
                'hargaMax' => 50000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kedai kopi dengan fokus pada kualitas roasting dan suasana nyaman untuk penikmat kopi sejati.',
            ],
            [
                'namaCafe' => 'De Ngokow Coffee',
                'gambarCafe' => 'de ngokoww.jpg',
                'alamatCafe' => 'Pendopo Ndalem Pujokusuman, Jl. Brigjen Katamso, Keparakan, Mergangsan, Yogyakarta City, Special Region of Yogyakarta 55152',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.81267437,
                'longitude' => 110.36922500,
                'hargaMin' => 15000,
                'hargaMax' => 35000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Tempat santai dengan suasana tradisional Jawa yang menawarkan kopi dan hidangan ringan.',
            ],
            [
                'namaCafe' => 'Sunset Coffee and Eatery',
                'gambarCafe' => 'sunset.jpg',
                'alamatCafe' => 'Jl. Nologaten, Nologaten, Condongcatur, YK, Yogyakarta, Daerah Istimewa Yogyakarta 55281',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.77383998,
                'longitude' => 110.40236005,
                'hargaMin' => 10000,
                'hargaMax' => 34000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe kasual dengan suasana outdoor dan pemandangan sunset terbaik.',
            ],
            [
                'namaCafe' => 'Coklat Cafe',
                'gambarCafe' => 'coklat cafe.jpg',
                'alamatCafe' => 'Jl. Cik Di Tiro No.19, Terban, Kec. Gondokusuman, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55223',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.77868003,
                'longitude' => 110.37589144,
                'hargaMin' => 18000,
                'hargaMax' => 75000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Pilihan ideal untuk pecinta coklat dengan suasana nyaman di tengah kota.',
            ],
            [
                'namaCafe' => 'Karta Coffee and Eatery',
                'gambarCafe' => 'karta.jpg',
                'alamatCafe' => 'Karta Coffee & Eatery, Jl. Malioboro. 52-58, Suryatmajan, Danurejan Plaza Malioboro, Lt. 1 Unit 13-16, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55213',
                'lokasi_area' => 'Yogyakarta',
                'latitude' => -7.79344469,
                'longitude' => 110.36711147,
                'hargaMin' => 10000,
                'hargaMax' => 75000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe modern di Malioboro dengan suasana nyaman dan beragam pilihan menu.',
            ],
            [
                'namaCafe' => 'Estuary Cafe',
                'gambarCafe' => 'estuary.jpg',
                'alamatCafe' => 'Gang Code 3, Karangjati Wetan, No.170 C, Monjali St, RT.06/RW.45, Gemawang, Sinduadi, Mlati, Sleman Regency, Special Region of Yogyakarta 55283',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.76327634,
                'longitude' => 110.37045383,
                'hargaMin' => 7000,
                'hargaMax' => 99000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Tempat nyaman untuk bekerja dan nongkrong dengan pilihan menu beragam.',
            ],
            [
                'namaCafe' => 'Mula Cafe and Eatery',
                'gambarCafe' => 'mula cafe.jpg',
                'alamatCafe' => 'Jl. Baru Mulungan, Gilingan, Sendangadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55285',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.74710741,
                'longitude' => 110.42921393,
                'hargaMin' => 18000,
                'hargaMax' => 29000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe dengan suasana cozy untuk nongkrong dan mengerjakan tugas.',
            ],
            [
                'namaCafe' => 'Cafe Brick',
                'gambarCafe' => 'cafe brick.png',
                'alamatCafe' => 'Jl. Damai No.8, Tambakan, Sinduharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.73436681,
                'longitude' => 110.39422571,
                'hargaMin' => 18000,
                'hargaMax' => 238000,
                'kebutuhan' => '{"kerja": true, "nugas": false, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Hidangan internasional di kedai bertema Inggris yang elegan.',
            ],
            [
                'namaCafe' => 'Kala Countryside Jogja',
                'gambarCafe' => 'kala countryside.jpg',
                'alamatCafe' => 'Jl. Baru Mulungan, Gilingan, Sendangadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55285',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.72553827,
                'longitude' => 110.36715586,
                'hargaMin' => 25000,
                'hargaMax' => 80000,
                'kebutuhan' => '{"kerja": false, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe dengan suasana pedesaan yang asri dan nyaman.',
            ],
            [
                'namaCafe' => 'Gemati Cafe and Space Yogyakarta',
                'gambarCafe' => 'gemati.jpg',
                'alamatCafe' => 'Jl. Sidomukti, Tiyosan, Condongcatur, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55281',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.73470290,
                'longitude' => 110.39994535,
                'hargaMin' => 15000,
                'hargaMax' => 30000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe dengan suasana yang mendukung untuk bekerja, belajar, dan rapat.',
            ],
            [
                'namaCafe' => 'Obie Cafe and Space',
                'gambarCafe' => 'obie.jpg',
                'alamatCafe' => 'Jl. Pogung Raya, Pogung Kidul, Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55284',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.75638197,
                'longitude' => 110.37540067,
                'hargaMin' => 16000,
                'hargaMax' => 30000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Ruang santai dengan suasana hangat untuk bekerja dan nongkrong.',
            ],
            [
                'namaCafe' => 'Kaktus Coffee Place',
                'gambarCafe' => 'kaktus.jpg',
                'alamatCafe' => 'Jl. Gondang Raya No.4-5, RT.08/RW.63, Kentungan, Condongcatur, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55283',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.75620228,
                'longitude' => 110.39257224,
                'hargaMin' => 18000,
                'hargaMax' => 37000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe bernuansa industrial dengan menu kopi inovatif dan makanan ringan.',
            ],
            [
                'namaCafe' => 'Agoge Cafe',
                'gambarCafe' => 'agoge.jpeg',
                'alamatCafe' => 'Jl. Bima Jl. Panggungsari No.164f, Wonorejo, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.73747900,
                'longitude' => 110.37970548,
                'hargaMin' => 20000,
                'hargaMax' => 55000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Tempat ideal untuk rapat, belajar, atau sekadar menikmati kopi.',
            ],
            [
                'namaCafe' => 'Astajava Coffee and Roastery',
                'gambarCafe' => 'astajava.jpg',
                'alamatCafe' => 'Tambak Rejo, Sariharjo, Dusun, Tambak Rejo, wonokerso, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.71617134,
                'longitude' => 110.38389650,
                'hargaMin' => 15000,
                'hargaMax' => 29000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe sekaligus roastery dengan pilihan kopi berkualitas tinggi.',
            ],
            [
                'namaCafe' => 'Eternity Coffee',
                'gambarCafe' => 'eternity.jpg',
                'alamatCafe' => 'Jalan Kaliurang KM 12 Ngaglik, Candi Karang, Sardonoharjo, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55281',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.70494289,
                'longitude' => 110.41306834,
                'hargaMin' => 16000,
                'hargaMax' => 28000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe 24 jam yang cocok untuk belajar, rapat, atau bersantai.',
            ],
            [
                'namaCafe' => 'Eskala Eatery Bar and Coffee',
                'gambarCafe' => 'eskala.jpg',
                'alamatCafe' => 'Jl. Palagan Tentara Pelajar, Tegal Rejo, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.72576422,
                'longitude' => 110.38185964,
                'hargaMin' => 20000,
                'hargaMax' => 370000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Cafe modern dengan suasana nyaman untuk berbagai aktivitas seperti kerja, nugas, atau nongkrong.',
            ],
            [
                'namaCafe' => 'Aming Coffee',
                'gambarCafe' => 'aming.jpg',
                'alamatCafe' => 'Jl. Gito Gati Jl. Grojogan No.Km. 1, Penggung, Tridadi, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55511',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.72058157,
                'longitude' => 110.36290883,
                'hargaMin' => 9000,
                'hargaMax' => 45000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe dengan kopi berkualitas dan suasana yang cocok untuk nugas atau santai bersama teman.',
            ],
            [
                'namaCafe' => 'Sleman Cafe',
                'gambarCafe' => 'sleman cafe.jpg',
                'alamatCafe' => 'Jl. Bhayangkara, Krapyak, Triharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55514',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.69630962,
                'longitude' => 110.34141348,
                'hargaMin' => 1000,
                'hargaMax' => 15000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => false, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe 24 jam dengan harga terjangkau, cocok untuk nongkrong santai kapan saja.',
            ],
            [
                'namaCafe' => 'Ruminate Coffee and Roastery',
                'gambarCafe' => 'ruminate.jpg',
                'alamatCafe' => 'Jl. Lempongsari No.111, Sumberan, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.75042142,
                'longitude' => 110.37405313,
                'hargaMin' => 23000,
                'hargaMax' => 175000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Tempat yang sempurna untuk pecinta kopi, dengan suasana yang nyaman untuk bekerja atau bersantai.',
            ],
            [
                'namaCafe' => 'Warmindo Biji Daun',
                'gambarCafe' => 'warmindo bijdaun.jpg',
                'alamatCafe' => 'Jl. Jugang Pangukan, Panglikan, Tridadi, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55511',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.71840016,
                'longitude' => 110.34758345,
                'hargaMin' => 4000,
                'hargaMax' => 20000,
                'kebutuhan' => json_encode(["kerja" => false, "nugas" => false, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Warmindo dengan menu murah meriah, cocok untuk tempat nongkrong santai bersama teman.',
            ],
            [
                'namaCafe' => 'Phinisi Cafe Jogja',
                'gambarCafe' => 'phinisi.jpg',
                'alamatCafe' => 'Jl. Candi Gebang, Beran Kidul, Beran, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55511',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.71848629,
                'longitude' => 110.35753431,
                'hargaMin' => 10000,
                'hargaMax' => 80000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe unik dengan suasana tenang dan menu bervariasi untuk berbagai aktivitas.',
            ],
            [
                'namaCafe' => 'Dailyfavor Coffee',
                'gambarCafe' => 'daily favor.png',
                'alamatCafe' => 'Jl. Watugede No.69, Wonorejo, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.73307019,
                'longitude' => 110.38161882,
                'hargaMin' => 25000,
                'hargaMax' => 50000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe minimalis dengan kopi pilihan, cocok untuk bekerja atau bersantai.',
            ],
            [
                'namaCafe' => 'Aloha Coffee',
                'gambarCafe' => 'aloha.jpg',
                'alamatCafe' => '786R+V48 Daerah Istimewah, Area Sawah, Tlogoadi, Mlati, Sleman Regency, Special Region of Yogyakarta',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.73749054,
                'longitude' => 110.34048773,
                'hargaMin' => 10000,
                'hargaMax' => 49000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe asri di area sawah, cocok untuk mencari ketenangan sambil menikmati kopi.',
            ],
            [
                'namaCafe' => 'Epic Coffee and Epilog Furniture',
                'gambarCafe' => 'epic coffee.jpg',
                'alamatCafe' => 'Jl. Palagan Tentara Pelajar No.29, Mudal, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.73376915,
                'longitude' => 110.37857925,
                'hargaMin' => 12000,
                'hargaMax' => 148000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Cafe unik dengan konsep furnitur epilog, ideal untuk rapat, bekerja, atau bersantai.',
            ],
            [
                'namaCafe' => 'Samasta Coffee',
                'gambarCafe' => 'samasta.jpg',
                'alamatCafe' => 'Pondok, Condongcatur, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55281',
                'lokasi_area' => 'Sleman',
                'latitude' => -7.74202819,
                'longitude' => 110.40560911,
                'hargaMin' => 15000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe modern di Condongcatur, cocok untuk nugas atau bersantai dengan teman.',
            ],
            [
                'namaCafe' => 'Taman Eatu Cafe and Resort',
                'gambarCafe' => 'taman eatu_watu.jpg',
                'alamatCafe' => 'Bolang, Girikarto, Kec. Panggang, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55872',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -8.10650093,
                'longitude' => 110.46295744,
                'hargaMin' => 10000,
                'hargaMax' => 100000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe dengan pemandangan alam yang cocok untuk bersantai bersama keluarga atau teman.',
            ],
            [
                'namaCafe' => 'Sintas Coffee',
                'gambarCafe' => 'sintas.jpg',
                'alamatCafe' => 'Kernen, RT.005/RW.003, Ngunut, Kec. Playen, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55861',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.94790116,
                'longitude' => 110.53965097,
                'hargaMin' => 5000,
                'hargaMax' => 25000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kedai kopi kecil dengan suasana tenang untuk belajar atau bekerja.',
            ],
            [
                'namaCafe' => 'Kopi Panggang dan Resto',
                'gambarCafe' => 'kopi panggang.jpg',
                'alamatCafe' => 'Jl. Siluk Panggang, Sumber, Girisuko, Kec. Panggang, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55872',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.97672499,
                'longitude' => 110.41585217,
                'hargaMin' => 50000,
                'hargaMax' => 150000,
                'kebutuhan' => json_encode(["kerja" => false, "nugas" => false, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Resto yang menawarkan berbagai makanan dan minuman dengan tempat yang luas.',
            ],
            [
                'namaCafe' => 'Roetin Coffee',
                'gambarCafe' => 'roetin.jpg',
                'alamatCafe' => 'Trimulyo I, Kepek, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55813',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.97030594,
                'longitude' => 110.59686719,
                'hargaMin' => 1000,
                'hargaMax' => 25000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe dengan konsep modern dan pilihan kopi yang beragam.',
            ],
            [
                'namaCafe' => 'Pule Coffee and Eatery',
                'gambarCafe' => 'pule.jpg',
                'alamatCafe' => 'Jl. Mgr. Sugiyo Pranoto No.23a, Purwosari, Baleharjo, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55881',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.97222797,
                'longitude' => 110.60728744,
                'hargaMin' => 25000,
                'hargaMax' => 50000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Kafe dengan suasana cozy, cocok untuk berbagai aktivitas seperti bekerja atau bersantai.',
            ],
            [
                'namaCafe' => 'Kopi Kenang by Mc Cafe',
                'gambarCafe' => 'kopi kenang.jpg',
                'alamatCafe' => '5, Jl. Jogja - Wonosari No.km, RW.3, Bandung, Kec. Playen, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55861',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.92907575,
                'longitude' => 110.56778764,
                'hargaMin' => 5000,
                'hargaMax' => 20000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kedai kopi dengan lokasi strategis dan suasana santai.',
            ],
            [
                'namaCafe' => 'Katamata Coffee and Roastery',
                'gambarCafe' => 'katamata.jpg',
                'alamatCafe' => 'Jl. Karangmojo - Wonosari No.13, Selang 4, Selang IV, Selang, Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55851',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.96239743,
                'longitude' => 110.62219688,
                'hargaMin' => 1000,
                'hargaMax' => 25000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kedai kopi dengan fokus pada kualitas biji kopi dan suasana nyaman.'
            ],
            [
                'namaCafe' => 'Ding\'s Coffee and Eatery',
                'gambarCafe' => 'dings.jpg',
                'alamatCafe' => 'Jl. Wonosari - Yogyakarta, KM 1, Siyono Kecamatan Playen, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55861',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.95104894,
                'longitude' => 110.58715114,
                'hargaMin' => 25000,
                'hargaMax' => 50000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Kafe modern dengan menu beragam dan tempat nyaman.'
            ],
            [
                'namaCafe' => 'Mountain Pleasure Coffee',
                'gambarCafe' => 'mountain pleasure.jpg',
                'alamatCafe' => 'Tegalmulyo RT 08/05, Kepek, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55813',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.96133379,
                'longitude' => 110.59500667,
                'hargaMin' => 25000,
                'hargaMax' => 50000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => false, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Restoran dengan pemandangan indah dan menu makanan serta minuman premium.'
            ],
            [
                'namaCafe' => 'Warung Kopi Masbro',
                'gambarCafe' => 'warung kopi masbro.jpg',
                'alamatCafe' => 'Brambang, Semoyo, Kec. Patuk, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55792',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.85587840,
                'longitude' => 110.47343547,
                'hargaMin' => 5000,
                'hargaMax' => 25000,
                'kebutuhan' => json_encode(["kerja" => false, "nugas" => false, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe 24 jam dengan suasana santai untuk bersantai bersama teman.'
            ],
            [
                'namaCafe' => 'Sunset Del Coffee',
                'gambarCafe' => 'sunset del.jpg',
                'alamatCafe' => 'Jl. Dlingo-Patuk, Brambang, Semoyo, Kec. Patuk, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55862',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.8534634769243645,
                'longitude' => 110.47527649347269,
                'hargaMin' => 25000,
                'hargaMax' => 50000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe dengan pemandangan sunset yang indah, cocok untuk menikmati sore.'
            ],
            [
                'namaCafe' => 'Vagida Coffee',
                'gambarCafe' => 'vagida.jpg',
                'alamatCafe' => 'Bansari Rt. 01/ Rw. 04, Kepek, Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55813',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.96848844,
                'longitude' => 110.59178221,
                'hargaMin' => 5000,
                'hargaMax' => 15000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => false, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe sederhana dengan harga terjangkau, cocok untuk tempat santai.'
            ],
            [
                'namaCafe' => 'Stiff Return',
                'gambarCafe' => 'stiff.jpg',
                'alamatCafe' => 'Gadungsari, Wonosari, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55851',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.966776544878544,
                'longitude' => 110.60684188235392,
                'hargaMin' => 5000,
                'hargaMax' => 25000,
                'kebutuhan' => json_encode(["kerja" => false, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe yang nyaman untuk malam hari, suasana yang tenang untuk ngobrol.'
            ],
            [
                'namaCafe' => 'Kopita/Kopikita',
                'gambarCafe' => 'kopita.jpg',
                'alamatCafe' => 'Purwosari, Baleharjo, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55881',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.97385087,
                'longitude' => 110.60665415,
                'hargaMin' => 15000,
                'hargaMax' => 50000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe dengan konsep modern, ideal untuk kerja atau tugas.'
            ],
            [
                'namaCafe' => 'D\'Teko',
                'gambarCafe' => 'dteko.jpg',
                'alamatCafe' => 'Jl. Pudak No.42, Pandansari, Wonosari, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55851',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.96520185,
                'longitude' => 110.60892397,
                'hargaMin' => 3000,
                'hargaMax' => 12000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => false]),
                'deskripsi' => 'Pilihan tepat untuk diskusi santai atau menikmati teh sore.'
            ],
            [
                'namaCafe' => 'Dini Hari Kopi',
                'gambarCafe' => 'dini hari.jpg',
                'alamatCafe' => 'Jl. Kenanga No.19, Purbosari, Wonosari, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55851',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.96600444,
                'longitude' => 110.60570215,
                'hargaMin' => 10000,
                'hargaMax' => 13000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Buka hingga tengah malam, cocok untuk kegiatan larut malam.'
            ],
            [
                'namaCafe' => 'Kondang Coffee',
                'gambarCafe' => 'kondang.png',
                'alamatCafe' => 'Jl. KH Agus Salim No.101, Ledoksari, Kepek, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55812',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.95659901,
                'longitude' => 110.59271762,
                'hargaMin' => 8000,
                'hargaMax' => 25000,
                'kebutuhan' => json_encode(["kerja" => false, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe cozy untuk nongkrong sore hingga malam hari.'
            ],
            [
                'namaCafe' => 'Omah Kayu Wonosari',
                'gambarCafe' => 'omah kayu.jpg',
                'alamatCafe' => 'Jl. Pemuda No.235, Gadungsari, Wonosari, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55851',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.96515499,
                'longitude' => 110.60587448,
                'hargaMin' => 10000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => false]),
                'deskripsi' => 'Kafe dengan ruang kerja yang nyaman dan tenang.'
            ],
            [
                'namaCafe' => 'Kopi Empat Tigabelas',
                'gambarCafe' => 'kopi empat.jpg',
                'alamatCafe' => 'Jl. Dewandaru No.58, Madusari, Wonosari, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55813',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.96868675,
                'longitude' => 110.60135438,
                'hargaMin' => 8000,
                'hargaMax' => 15000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Kafe 24 jam yang cocok untuk semua kebutuhan.'
            ],
            [
                'namaCafe' => 'Kedai Kopi 69 Wonosari',
                'gambarCafe' => 'kedai kopi 69.jpg',
                'alamatCafe' => 'Jl. Ir Jl. Insinyur Darmakum Darmokusumo, Wukirsari, Baleharjo, Kec. Wonosari, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55811',
                'lokasi_area' => 'Gunung Kidul',
                'latitude' => -7.97805545,
                'longitude' => 110.61674256,
                'hargaMin' => 8000,
                'hargaMax' => 20000,
                'kebutuhan' => json_encode(["kerja" => false, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kedai kopi dengan suasana santai, ideal untuk mengobrol.'
            ],
            [
                'namaCafe' => 'Marron Cafe',
                'gambarCafe' => 'marron.jpg',
                'alamatCafe' => '752Q+RMG, Jl. Nanggulan - Samigaluh, Tileng, Pendoworejo, Kec. Girimulyo, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.74779377,
                'longitude' => 110.18984776,
                'hargaMin' => 3000,
                'hargaMax' => 35000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe nyaman untuk nongkrong dan mengerjakan tugas, dengan suasana sejuk di daerah Samigaluh.'
            ],
            [
                'namaCafe' => 'Terraloka',
                'gambarCafe' => 'terraloka.jpg',
                'alamatCafe' => 'Jl. Raya Kaligesing, Krikil, Pendoworejo, Kec. Girimulyo, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55674',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.74978912,
                'longitude' => 110.19259012,
                'hargaMin' => 10000,
                'hargaMax' => 72000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe modern dengan berbagai pilihan makanan dan minuman yang cocok untuk bersantai.'
            ],
            [
                'namaCafe' => 'Kopi Ampirono',
                'gambarCafe' => 'ampirono.jpg',
                'alamatCafe' => '65XR+WG9, Jl. Raya Kaligesing, Tileng, Pendoworejo, Kec. Girimulyo, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55674',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.75001434,
                'longitude' => 110.19223444,
                'hargaMin' => 3000,
                'hargaMax' => 25000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => false, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kopi Ampirono menawarkan suasana khas pedesaan dengan pemandangan indah.'
            ],
            [
                'namaCafe' => 'Tabebuya Cafe',
                'gambarCafe' => 'tabebuya.jpeg',
                'alamatCafe' => 'Jl. Sanun, Area Sawah, Wates, Kec. Wates, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55651',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.85443936,
                'longitude' => 110.15540453,
                'hargaMin' => 12000,
                'hargaMax' => 33000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kafe unik yang berada di tengah area persawahan, cocok untuk istirahat sore.'
            ],
            [
                'namaCafe' => 'Karsa Coffee and Space',
                'gambarCafe' => 'karsa.jpg',
                'alamatCafe' => 'Jl. Pahlawan No.36, Gerawulan, Giri Peni, Kec. Wates, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55612',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.86778323,
                'longitude' => 110.15644928,
                'hargaMin' => 14000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Kafe yang menyediakan tempat untuk kerja dan rapat dengan fasilitas lengkap.'
            ],
            [
                'namaCafe' => 'Terraskota Coffee and Kitchen',
                'gambarCafe' => 'terraskota.jpeg',
                'alamatCafe' => 'Jl. Pahlawan No.2-13, Sideman, Giri Peni, Kec. Wates, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55651',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.88002289,
                'longitude' => 110.15408598,
                'hargaMin' => 13000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Terraskota Coffee and Kitchen menyajikan menu modern dengan suasana cozy.'
            ],
            [
                'namaCafe' => 'Joglo Girli Resto and Cafe',
                'gambarCafe' => 'joglo girli.jpg',
                'alamatCafe' => 'Kembang, Margosari, Kec. Pengasih, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55652',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.84702569,
                'longitude' => 110.17665615,
                'hargaMin' => 5000,
                'hargaMax' => 28000,
                'kebutuhan' => json_encode(["kerja" => false, "nugas" => false, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Resto dan kafe bergaya tradisional dengan menu lokal yang lezat.'
            ],
            [
                'namaCafe' => 'Toska Kahve',
                'gambarCafe' => 'toska kahve.jpg',
                'alamatCafe' => 'Jl. Bhayangkara No.17, Terbah, Wates, Kec. Wates, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55651',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.85594585,
                'longitude' => 110.16242627,
                'hargaMin' => 17000,
                'hargaMax' => 24000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => false, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Kafe dengan interior minimalis, cocok untuk rapat kecil atau sekadar ngopi.'
            ],
            [
                'namaCafe' => 'Kedai Kopi Suroloyo',
                'gambarCafe' => 'suroloyo.jpg',
                'alamatCafe' => 'Keceme, Gerbosari, Kec. Samigaluh, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.64744240,
                'longitude' => 110.18199811,
                'hargaMin' => 3000,
                'hargaMax' => 15000,
                'kebutuhan' => json_encode(["kerja" => false, "nugas" => false, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Kedai kopi dengan suasana khas pegunungan dan udara segar.'
            ],
            [
                'namaCafe' => 'Kripala Dekso Coffee and Resto',
                'gambarCafe' => 'kripala dekso.jpg',
                'alamatCafe' => 'Jl. Persandian, Ngipik Rejo, Banjararum, Kec. Kalibawang, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55672',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.71502706,
                'longitude' => 110.21808195,
                'hargaMin' => 3000,
                'hargaMax' => 110000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => true, "nongkrong" => true]),
                'deskripsi' => 'Kafe dan resto dengan pilihan menu lengkap, cocok untuk berbagai kebutuhan.'
            ],
            [
                'namaCafe' => 'Otentik Resto and Cafe',
                'gambarCafe' => 'otentik.jpg',
                'alamatCafe' => '35X8+QGP, JL. Brosot - Wates.Km. 2, Dusun 1, Gotakan 1, Jalan, Dusun 1, Gotakan, Kec. Panjatan, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55655',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.90042507,
                'longitude' => 110.16754349,
                'hargaMin' => 2000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(['kerja' => true, 'nugas' => true, 'rapat' => true, 'nongkrong' => true]),
                'deskripsi' => 'Restoran nyaman dengan suasana santai, cocok untuk makan siang, bekerja, atau berkumpul dengan teman.',
            ],
            [
                'namaCafe' => 'Kopi Klotok Menoreh',
                'gambarCafe' => 'kopi klotok.jpg',
                'alamatCafe' => 'Jl. Raya Kaligesing, Kenteng, Kembang, Kec. Nanggulan, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55671',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.75021296,
                'longitude' => 110.19840616,
                'hargaMin' => 7000,
                'hargaMax' => 29000,
                'kebutuhan' => json_encode(['kerja' => true, 'nugas' => true, 'rapat' => false, 'nongkrong' => true]),
                'deskripsi' => 'Menawarkan kopi tradisional dengan pemandangan menawan khas perbukitan Menoreh.',
            ],
            [
                'namaCafe' => 'Buron\'s Coffee and Kitchen',
                'gambarCafe' => 'burons.jpg',
                'alamatCafe' => 'Jl. Margosari, Kembang, Margosari, Kec. Pengasih, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55652',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.84661672,
                'longitude' => 110.17692235,
                'hargaMin' => 3000,
                'hargaMax' => 22000,
                'kebutuhan' => json_encode(['kerja' => true, 'nugas' => true, 'rapat' => true, 'nongkrong' => true]),
                'deskripsi' => 'Kafe dengan desain modern dan menu yang terjangkau, cocok untuk segala aktivitas.',
            ],
            [
                'namaCafe' => 'Parra Coffee',
                'gambarCafe' => 'parra.jpg',
                'alamatCafe' => 'Josutan, Karangsari, Kec. Pengasih, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.86979894,
                'longitude' => 110.12680643,
                'hargaMin' => 5000,
                'hargaMax' => 45000,
                'kebutuhan' => json_encode(['kerja' => true, 'nugas' => true, 'rapat' => true, 'nongkrong' => true]),
                'deskripsi' => 'Suasana cozy untuk menikmati kopi sambil bekerja atau bersantai.',
            ],
            [
                'namaCafe' => 'Kloop Coffee',
                'gambarCafe' => 'kloop.jpg',
                'alamatCafe' => 'Jl. Pantai Glagah, Kadilangu Kidul, Temon Kulon, Kec. Temon, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55654',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.89020924,
                'longitude' => 110.07811549,
                'hargaMin' => 5000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(['kerja' => true, 'nugas' => true, 'rapat' => false, 'nongkrong' => true]),
                'deskripsi' => 'Tempat yang strategis dekat Pantai Glagah, cocok untuk menikmati kopi dengan suasana pantai.',
            ],
            [
                'namaCafe' => 'Kampoeng Cafe',
                'gambarCafe' => 'kampoeng.jpg',
                'alamatCafe' => 'Wonolopo RT033 /Rw015, Gulurejo, Kec. Lendah, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55663',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.91159817,
                'longitude' => 110.26161145,
                'hargaMin' => 2000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(['kerja' => false, 'nugas' => true, 'rapat' => true, 'nongkrong' => true]),
                'deskripsi' => 'Kafe unik yang menyajikan suasana pedesaan dengan menu lokal yang khas.',
            ],
            [
                'namaCafe' => 'Kopi Menoreh Pak Rohmat',
                'gambarCafe' => 'menoreh pak rohmat.jpg',
                'alamatCafe' => 'Madigondo, RT.26/RW.10, Madigondo, Sidoharjo, Kec. Samigaluh, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55673',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.66177970,
                'longitude' => 110.20611348,
                'hargaMin' => 3500,
                'hargaMax' => 200000,
                'kebutuhan' => json_encode(['kerja' => false, 'nugas' => false, 'rapat' => true, 'nongkrong' => true]),
                'deskripsi' => 'Nikmati kopi otentik khas Menoreh di tempat yang sederhana namun menyenangkan.',
            ],
            [
                'namaCafe' => 'Kopi Ingkar Janji',
                'gambarCafe' => 'ingkar janji.jpg',
                'alamatCafe' => 'Jl. Raya Kaligesing No.17, Tileng, Pendoworejo, Kec. Girimulyo, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55674',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.74917201,
                'longitude' => 110.18958403,
                'hargaMin' => 25000,
                'hargaMax' => 50000,
                'kebutuhan' => json_encode(['kerja' => true, 'nugas' => false, 'rapat' => true, 'nongkrong' => true]),
                'deskripsi' => 'Kafe yang terkenal dengan menu kopi spesial dan suasana yang nyaman.',
            ],
            [
                'namaCafe' => 'Tomoro Coffee - Wates',
                'gambarCafe' => 'tomoro.jpg',
                'alamatCafe' => '45R3+4FF Driyan, RT.060/RW.028, Area Sawah, Wates, Kec. Wates, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55651',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.85947617,
                'longitude' => 110.15440356,
                'hargaMin' => 22000,
                'hargaMax' => 35000,
                'kebutuhan' => json_encode(['kerja' => true, 'nugas' => true, 'rapat' => true, 'nongkrong' => true]),
                'deskripsi' => 'Tempat nongkrong modern dengan pilihan kopi berkualitas dan lokasi strategis.',
            ],
            [
                'namaCafe' => "D'SrupaT Sruput",
                'gambarCafe' => 'dsrupat.jpg',
                'alamatCafe' => '45R5+MGM, Jl. Tamtama, Terbah, Wates, Kec. Wates, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55611',
                'lokasi_area' => 'Kulon Progo',
                'latitude' => -7.85813391,
                'longitude' => 110.15968732,
                'hargaMin' => 7000,
                'hargaMax' => 21000,
                'kebutuhan' => json_encode(['kerja' => true, 'nugas' => true, 'rapat' => false, 'nongkrong' => true]),
                'deskripsi' => 'Pilihan tepat untuk menikmati minuman hangat di suasana santai.',
            ],
            [
                'namaCafe' => 'Arion Coffee and Tea',
                'gambarCafe' => 'arion.jpg',
                'alamatCafe' => 'Karangbayam, Bantul, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55711',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.89478917,
                'longitude' => 110.33449644,
                'hargaMin' => 15000,
                'hargaMax' => 30000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe nyaman dengan suasana santai, cocok untuk nongkrong dan nugas.'
            ],
            [
                'namaCafe' => 'Haia Space',
                'gambarCafe' => 'haia.jpg',
                'alamatCafe' => 'Jl. Jend. Sudirman No.38, Bantul Wr., Bantul, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55711',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.88267356,
                'longitude' => 110.33285680,
                'hargaMin' => 20000,
                'hargaMax' => 50000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Ruang kreatif yang cocok untuk kerja, nugas, maupun rapat kecil.'
            ],
            [
                'namaCafe' => 'Kohi Coffee House and Space',
                'gambarCafe' => 'kohi.jpg',
                'alamatCafe' => 'Jl. May Jen. Sutoyo, Nyangkringan, Bantul, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55711',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.88532553,
                'longitude' => 110.33321143,
                'hargaMin' => 25000,
                'hargaMax' => 60000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe modern dengan area luas yang nyaman untuk bekerja atau sekedar bersantai.'
            ],
            [
                'namaCafe' => 'Poma Coffee and Resto',
                'gambarCafe' => 'poma.jpg',
                'alamatCafe' => 'Jl. Marsda Adisucipto No.47, Area Sawah, Trirenggo, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 40115',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.89540794,
                'longitude' => 110.33656931,
                'hargaMin' => 20000,
                'hargaMax' => 70000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe dengan menu makanan lengkap dan suasana yang santai untuk nongkrong bersama teman.'
            ],
            [
                'namaCafe' => '23 Coffee and Eatery',
                'gambarCafe' => 'duatiga.jpg',
                'alamatCafe' => 'Kojo, RT.23, Area Sawah, Pendowoharjo, Kec. Sewon, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55185',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.87276405,
                'longitude' => 110.34681635,
                'hargaMin' => 15000,
                'hargaMax' => 40000,
                'kebutuhan' => '{"kerja": false, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe minimalis yang cocok untuk menikmati waktu sore hingga malam.'
            ],
            [
                'namaCafe' => 'Paddys Cafe and Eatery',
                'gambarCafe' => 'paddys.jpg',
                'alamatCafe' => 'Jl. Pramuka No.10, Krandohan, Trirenggo, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55714',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.87833519,
                'longitude' => 110.33772544,
                'hargaMin' => 18000,
                'hargaMax' => 50000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe dengan menu beragam dan suasana yang hangat untuk semua kebutuhan.'
            ],
            [
                'namaCafe' => 'Bee Dyoti Hidden Cafe Puncak Bibis',
                'gambarCafe' => 'bee dyoti.jpg',
                'alamatCafe' => '48W6+X6 Bibis, RT 05, Bangunjiwo, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55181',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.85241290,
                'longitude' => 110.31106250,
                'hargaMin' => 15000,
                'hargaMax' => 35000,
                'kebutuhan' => '{"kerja": false, "nugas": false, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe tersembunyi di puncak Bibis dengan pemandangan indah dan suasana tenang.'
            ],
            [
                'namaCafe' => 'Memoria Cafe and Event Space',
                'gambarCafe' => 'memoria.jpg',
                'alamatCafe' => 'Jl. Srandakan No.RT 04, Gedongsari, Wijirejo, Kec. Pandak, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55761',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.90903794,
                'longitude' => 110.29750340,
                'hargaMin' => 25000,
                'hargaMax' => 80000,
                'kebutuhan' => '{"kerja": true, "nugas": false, "rapat": true, "nongkrong": true}',
                'deskripsi' => 'Kafe multifungsi yang cocok untuk rapat, acara, atau bersantai bersama keluarga.'
            ],
            [
                'namaCafe' => 'Temani Ngopi',
                'gambarCafe' => 'temai.jpg',
                'alamatCafe' => 'Jl. Urip Sumoharjo No.8, Bejen, Bantul, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55711',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.89151872,
                'longitude' => 110.32973317,
                'hargaMin' => 12000,
                'hargaMax' => 35000,
                'kebutuhan' => '{"kerja": true, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe dengan suasana nyaman untuk menemani waktu bekerja atau nugas.'
            ],
            [
                'namaCafe' => 'Kopi Tempuran',
                'gambarCafe' => 'tempuran.jpg',
                'alamatCafe' => 'Jl. Plataran No.9, Sembungan, Bangunjiwo, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.83534924,
                'longitude' => 110.34028230,
                'hargaMin' => 15000,
                'hargaMax' => 40000,
                'kebutuhan' => '{"kerja": false, "nugas": true, "rapat": false, "nongkrong": true}',
                'deskripsi' => 'Kafe dengan konsep outdoor di tepi sungai, cocok untuk menikmati waktu santai.'
            ],
            [
                'namaCafe' => 'savasana coffee',
                'gambarCafe' => 'savasana.png',
                'alamatCafe' => 'Jl. Selarong No.15a, Area Sawah, Pendowoharjo, Kec. Sewon, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55185',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.85854309,
                'longitude' => 110.33428422,
                'hargaMin' => 15000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Tempat nyaman dengan konsep minimalis yang cocok untuk bekerja dan bersantai.'
            ],
            [
                'namaCafe' => 'java milk',
                'gambarCafe' => 'java milk.jpg',
                'alamatCafe' => 'Jl. Dr. Wahidin Sudiro Husodo No.78, Nogosari, Trirenggo, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55714',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.89396045,
                'longitude' => 110.34451713,
                'hargaMin' => 20000,
                'hargaMax' => 40000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Menyajikan beragam minuman berbasis susu dan kopi dengan suasana yang cozy.'
            ],
            [
                'namaCafe' => 'passion coffee',
                'gambarCafe' => 'passion.jpeg',
                'alamatCafe' => 'Jl. Kenanga No.7, Gedongan, Bangunjiwo, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.84183237,
                'longitude' => 110.32384707,
                'hargaMin' => 25000,
                'hargaMax' => 50000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Tempat unik untuk pecinta kopi dengan dekorasi menarik.'
            ],
            [
                'namaCafe' => 'javanesa coffee',
                'gambarCafe' => 'javanesa.jpg',
                'alamatCafe' => '489G+52V, Jl. Gatot Subroto, Kurahan, Bantul, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55711',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.88182254,
                'longitude' => 110.32597902,
                'hargaMin' => 15000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe yang menawarkan suasana santai dan nyaman dengan pilihan kopi khas.'
            ],
            [
                'namaCafe' => 'moonlight coffee',
                'gambarCafe' => 'moonlight.jpg',
                'alamatCafe' => 'Geneng, Panggungharjo, Kec. Sewon, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55188',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.85101499,
                'longitude' => 110.34944340,
                'hargaMin' => 20000,
                'hargaMax' => 40000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Pilihan yang sempurna untuk menikmati malam dengan kopi nikmat.'
            ],
            [
                'namaCafe' => 'moon cafe yogyakarta',
                'gambarCafe' => 'moon.jpg',
                'alamatCafe' => 'Jl. Sungapan No.4, Jetis, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55183',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.82989108,
                'longitude' => 110.32545434,
                'hargaMin' => 15000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe dengan suasana romantis untuk hangout bersama teman.'
            ],
            [
                'namaCafe' => 'lotus mio bangunjiwo restaurant',
                'gambarCafe' => 'lotus.jpg',
                'alamatCafe' => 'Mejing, Kalirandu, Bangunjiwo, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.84305190,
                'longitude' => 110.30587248,
                'hargaMin' => 30000,
                'hargaMax' => 60000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Restoran dengan berbagai pilihan menu dan pemandangan indah.'
            ],
            [
                'namaCafe' => 'pour over coffee indonesia',
                'gambarCafe' => 'pour over.jpg',
                'alamatCafe' => 'Karangjati RT. 05 Pedukuhan V Jetis Tamantirto Kasihan, Jetis, Tamantirto, Jetis, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55183',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.83445903,
                'longitude' => 110.32468040,
                'hargaMin' => 20000,
                'hargaMax' => 40000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Tempat terbaik untuk menikmati kopi specialty dengan suasana tenang.'
            ],
            [
                'namaCafe' => 'stako kopi paseban',
                'gambarCafe' => 'stako.jpg',
                'alamatCafe' => '487F+MQH, Jl. Gatot Subroto, Soropaten, Ringinharjo, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55281',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.88563550,
                'longitude' => 110.32385002,
                'hargaMin' => 15000,
                'hargaMax' => 30000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe lokal dengan berbagai pilihan kopi dan makanan ringan.'
            ],
            [
                'namaCafe' => 'nenas 114',
                'gambarCafe' => 'nenas.jpg',
                'alamatCafe' => 'Jl. Kh. Ahmad Dahlan No.17, Nyangkringan, Bantul, Kec. Bantul, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55711',
                'lokasi_area' => 'Bantul',
                'latitude' => -7.88930215,
                'longitude' => 110.32979570,
                'hargaMin' => 10000,
                'hargaMax' => 20000,
                'kebutuhan' => json_encode(["kerja" => true, "nugas" => true, "rapat" => false, "nongkrong" => true]),
                'deskripsi' => 'Cafe yang cocok untuk sarapan dan menikmati waktu santai di pagi hari.'
            ]
        ]);
    }
}
